// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Time after which we abort a request and try again on a fresh connection.
// 6s bisects the typical 12s TCP-retransmission spike caused by HTTP/2
// head-of-line blocking on Safari — the retry usually picks up a healthy
// connection and finishes faster than waiting out the original.
const REQUEST_TIMEOUT_MS = 6000;

function isIdempotent(method: string): boolean {
  const m = method.toUpperCase();
  return m === "GET" || m === "HEAD";
}

// Per-request timing/error breadcrumbs. Useful in dev/preview, noise in prod —
// gate behind import.meta.env.DEV so Vite tree-shakes the calls out of the
// production bundle. Set localStorage["supa-debug"] = "1" to opt back in.
const DEBUG_TIMING =
  import.meta.env.DEV ||
  (typeof localStorage !== "undefined" && localStorage.getItem("supa-debug") === "1");
const debugLog = (msg: string) => {
  if (DEBUG_TIMING) {
    // eslint-disable-next-line no-console
    console.log(msg);
  }
};

const timedFetch: typeof fetch = async (input, init) => {
  const url = typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
  const method = (init?.method ?? (input instanceof Request ? input.method : "GET")).toUpperCase();
  const short = url.replace(SUPABASE_URL, "").slice(0, 120);
  const canRetry = isIdempotent(method);

  // Non-idempotent requests (signup, profile update, event publish, …) cannot
  // safely be retried — aborting after 6s would leave the server having
  // already processed the request while the client thinks it failed. So we
  // skip the timeout entirely and let the browser's own (~60-120s) timeout
  // be the upper bound.
  if (!canRetry) {
    const t0 = performance.now();
    try {
      const response = await fetch(input, init);
      const ttfb = Math.round(performance.now() - t0);
      const tag = ttfb >= 2000 ? "🐢" : ttfb >= 500 ? "⚠️" : "✓";
      debugLog(`[supabase] ${tag} ${method} ${response.status} ${ttfb}ms ${short}`);
      return response;
    } catch (err) {
      const ttfb = Math.round(performance.now() - t0);
      debugLog(`[supabase] ✗ ${method} FAIL ${ttfb}ms ${short} — ${err instanceof Error ? err.message : String(err)}`);
      throw err;
    }
  }

  const userSignal = init?.signal ?? (input instanceof Request ? input.signal : undefined);
  const maxAttempts = 2;

  let lastError: unknown;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const t0 = performance.now();
    const controller = new AbortController();
    let timedOut = false;
    const timeoutId = setTimeout(() => {
      timedOut = true;
      controller.abort();
    }, REQUEST_TIMEOUT_MS);
    const onUserAbort = () => controller.abort();
    if (userSignal) {
      if (userSignal.aborted) controller.abort();
      else userSignal.addEventListener("abort", onUserAbort);
    }

    try {
      const response = await fetch(input, { ...init, signal: controller.signal });
      const ttfb = Math.round(performance.now() - t0);
      const tag = ttfb >= 2000 ? "🐢" : ttfb >= 500 ? "⚠️" : "✓";
      const note = attempt > 1 ? ` (retry ${attempt})` : "";
      debugLog(`[supabase] ${tag} ${method} ${response.status} ${ttfb}ms ${short}${note}`);
      return response;
    } catch (err) {
      lastError = err;
      const ttfb = Math.round(performance.now() - t0);
      if (timedOut && attempt < maxAttempts && !userSignal?.aborted) {
        debugLog(`[supabase] ⏱ ${method} TIMEOUT ${ttfb}ms ${short} — retrying`);
        continue;
      }
      const reason = timedOut ? "TIMEOUT" : userSignal?.aborted ? "ABORT" : "FAIL";
      debugLog(`[supabase] ✗ ${method} ${reason} ${ttfb}ms ${short} — ${err instanceof Error ? err.message : String(err)}`);
      throw err;
    } finally {
      clearTimeout(timeoutId);
      if (userSignal) userSignal.removeEventListener("abort", onUserAbort);
    }
  }

  throw lastError;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: timedFetch },
});